# .pre-commit-config.yaml file for https://github.com/zxdavb/ramses_rf
# last updated 2024-02-22, based on HA 2024.03.dev0

exclude: (^.secrets/|^docs/|^misc|tests/deprecated)

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff         # linter
      - id: ruff-format  # formatter

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    - id: python-check-blanket-noqa
    - id: python-check-blanket-type-ignore
    - id: python-no-log-warn

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    # id: check-json  # don't enable this one
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: local
    hooks:
      # entry: '[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+'  # email address

    - id: debugs
      name: check for DEBUG flags
      entry: '_DBG_.*=.*True'
      language: pygrep
      args: [-i]
      exclude: (.pre-commit-config.yaml|^tests/.*\.py$)  # avoid false +ve

    # - id: fixme
    #   name: check for FIXME flags
    #   entry: '#.*(FIXME|TODO)'
    #   language: pygrep
    #   args: [-i]
    #   exclude: (.pre-commit-config.yaml|^tests/.*\.py$)  # avoid false +ve

    - id: secrets
      name: check for secrets
      entry: '#.*(secret|password|pwd)'
      language: pygrep
      args: [-i]
      exclude: .pre-commit-config.yaml  # avoid false +ve

    # - id: private imports
    #   name: check for private imports
    #   entry: 'from .* import _.*'
    #   language: pygrep
    #   args: [-i]
    #   exclude: .pre-commit-config.yaml  # avoid false +ve

    # We do not use pre-commit/mirrors-mypy, as it comes with opinionated defaults
    # (like --ignore-missing-imports) and is difficult to configure to run
    # with the dependencies correctly installed.

    # - id: mypy
    #   name: check mypy
    #   entry: mypy
    #   language: python
    #   additional_dependencies: [voluptuous==0.14.1]
    #   types: [python]
    #   # use require_serial so that script is only called once per commit
    #   require_serial: true
    #   # Print the number of files as a sanity-check
    #   verbose: true
    #   args: ["--config-file", "./pyproject.toml"]

  # We do not use pre-commit/mirrors-mypy, as it comes with opinionated defaults
  # (like --ignore-missing-imports) and is difficult to configure to run
  # with the dependencies correctly installed.

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #   - id: mypy
  #     additional_dependencies: [voluptuous==0.14.1]
  #     args: ["--config-file", "./pyproject.toml"]
