name: Typing


on:
  push:
    branches: [ "master", "stable" ]
    paths: [
      ".github/workflows/type-type.yml",
      "src/**.py", "src/**/py.typed",
      "tests/**.py",
    ]

  pull_request:
    branches: [ "master", "stable" ]
    paths: [
      ".github/workflows/type-type.yml",
      "src/**.py", "src/**/py.typed",
      "tests/**.py",
    ]

  workflow_dispatch:


jobs:
  type:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Check with mypy
        run: mypy

      - run: echo "🍏 This job's status is ${{ job.status }}."
