# This workflow will upload a Python Package using Hatch when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
# and: https://github.com/pypa/hatch/issues/669

name: Publish via Hatch

on:
  release:
    types: [published]

  workflow_dispatch:
  # for testing hatch

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install hatch
        run: pipx install hatch

      - name: Run tests
        run: hatch test

      - name: Build dist
        run: hatch build

      # - name: Publish on PyPi
        # run: hatch publish
        # with:
        #   user: __token__
        #   password: ${{ secrets.PYPI_API_TOKEN }}

      - run: echo "🍏 This job's status is ${{ job.status }}."
